# Generated by Django 4.0.5 on 2022-06-19 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userlog_apply_date_alter_userlog_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 17, 18, 51, 613149)),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='login_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 17, 18, 51, 613149)),
        ),
    ]
